#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'runit'
cookbook 'ohai', '1.1.8', :git => 'git://github.com/opscode-cookbooks/ohai.git'
cookbook 'chef-client'
cookbook 'ntp', '1.3.2', :git => 'git://github.com/opscode-cookbooks/ntp.git'
cookbook 'yum', '2.2.1', :git => 'git://github.com/opscode-cookbooks/yum.git'
cookbook 'build-essential', '1.3.4', :git => 'git://github.com/opscode-cookbooks/build-essential.git'
cookbook 'nodejs', '1.1.2', :git => 'git://github.com/mdxp/nodejs-cookbook.git'
cookbook 'zsh', '1.0.0', :git => 'git://github.com/opscode-cookbooks/zsh.git'
cookbook 'python', '1.2.2', :git => 'git://github.com/opscode-cookbooks/python.git'
=begin
cookbook 'tmux', '1.1.2', :git => 'git://github.com/opscode-cookbooks/tmux.git'
cookbook 'java', '1.10.0', :git => 'git://github.com/opscode-cookbooks/java.git'
cookbook 'git', '2.3.0', :git => 'git://github.com/opscode-cookbooks/git.git'
cookbook 'lvm', '0.8.6', :git => 'git://github.com/opscode-cookbooks/lvm.git'
cookbook 'vim', '1.0.2', :git => 'git://github.com/opscode-cookbooks/vim.git'
cookbook 'openssh', '1.1.4', :git => 'git://github.com/opscode-cookbooks/openssh.git'
cookbook 'htop', '0.1', :git => 'git://github.com/cookbooks/htop.git'
cookbook 'redis', '1.0.4', :git => 'git://github.com/cookbooks/hw-redis.git'
cookbook 'rvm', '0.9.1', :git => 'git://github.com/fnichol/chef-rvm.git'
=end
